"""Añadidos campos name, surname y phone_number a User

Revision ID: 73252efd5260
Revises: 6e779b3c0402
Create Date: 2025-10-09 21:44:09.495165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73252efd5260'
down_revision = '6e779b3c0402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
